mod 'puppet-nginx', '2.0.0'
mod 'puppetlabs-concat'
mod 'puppetlabs-translate'
mod 'puppetlabs-stdlib'

mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.12.0'
mod 'puppetlabs-apt', '7.6.0'
mod 'puppetlabs-powershell', '4.0.0'
mod 'puppetlabs-pwshlib', '0.5.1'
mod 'puppetlabs-reboot', '3.0.0'
